---


- name: Create MongoDB user and grant privileges
  become: true
  shell: |
    mongosh admin --eval '
    db.createUser({
      user: "mongo_user",
      pwd: "mongo_password",
      roles: [{ role: "root", db: "admin" }]
    })'


- name: Create MongoDB database
  become: true
  shell: |
    mongosh --username "{{ mongo_user }}" --password "{{ mongo_password }}" --authenticationDatabase "admin" --eval '
      db.getSiblingDB("{{dbname}}").createCollection("{{collection}}")'

- name: Insert documents into MongoDB collection
  become: true
  shell: |
    mongosh --username "{{ mongo_user }}" --password "{{ mongo_password }}" --authenticationDatabase "admin" --eval '
      db.getSiblingDB("{{dbname}}")."{{collection}}".insertMany([
        { "field1": "value1", "field2": "value2" },
        { "field1": "value3", "field2": "value4" }
      ])'







